name: Deploy Frontend

on:
  push:
    branches: [main, Frontend]
    paths:
      - 'Frontend/**'
      - '.github/workflows/deploy-frontend.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.NOTIFICATION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NOTIFICATION_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/frontend:$IMAGE_TAG -f Frontend/Dockerfile .
          docker push $ECR_REGISTRY/frontend:$IMAGE_TAG
          docker tag $ECR_REGISTRY/frontend:$IMAGE_TAG $ECR_REGISTRY/frontend:latest
          docker push $ECR_REGISTRY/frontend:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ecommerce-cluster_notifcation \
            --service frontend \
            --force-new-deployment \
            --region us-east-1